# Generated by Django 4.1.7 on 2023-02-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlanguage',
            name='language',
            field=models.CharField(choices=[('ar', 'Arab tili'), ('en', 'Ingliz tili'), ('ru', 'Rus tili'), ('uz', "O'zbek tili")], max_length=3),
        ),
    ]
