# Generated by Django 4.1.7 on 2023-04-04 20:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userlanguage_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='custom_id',
            field=models.CharField(db_index=True, default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=13, validators=[django.core.validators.RegexValidator(message='Raqam 13 ta belgidan iborat bolishi kerak. P.s: +998912345678', regex='^\\+998\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='userlanguage',
            name='language',
            field=models.CharField(choices=[('ar', 'Arabic'), ('en', 'English'), ('ru', 'Russian'), ('uz', 'Uzbek')], max_length=3),
        ),
        migrations.AlterField(
            model_name='userlanguage',
            name='level',
            field=models.CharField(choices=[('il', 'B2'), ('bo', 'Beginner'), ('er', 'Native'), ('oa', 'B1')], max_length=3),
        ),
    ]
