# Generated by Django 4.1.7 on 2023-03-21 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_remove_complaint_client_maincomplaint_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='create_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='update_date',
            new_name='updated_date',
        ),
    ]
