# Generated by Django 4.1.7 on 2023-04-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='custom_id',
            field=models.CharField(db_index=True, default=1, error_messages={'unique': 'A product with that custom_id already exists.'}, max_length=12),
            preserve_default=False,
        ),
    ]
