# Generated by Django 3.2 on 2023-02-14 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productfield_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfield',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_fields', to='products.product'),
        ),
    ]
